services:
  sip:
    image: livekit/sip
    network_mode: host
    environment:
      SIP_CONFIG_BODY: |
        api_key: 'API6UU3dpMyUfHC'
        api_secret: '3ESSoTCqNPJ9rBfD0HeLf5z6nxW0iemNVuH50kzeNenE'
        ws_url: 'ws://localhost:7880'
        redis:
          address: 'localhost:6379'
        sip_port: 5060
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: debug
