keyterms = [
    "BP Number",
    "Address",
    "Email",
    "Consumption",
    "Amount",
    "Name",
    "Mobile",
    "Email",
    "Address",
    "Bill Number",
    "Meter Number",
    "Customer Name",
    "Address",
    "Email",
    "Mobile Number",
    "Bill Date",
    "Previous Reading",
    "Current Reading",
    "Consumption",
    "Amount",
    "Due Date",
    "Late Fee",
    "Total Amount",
    "Outstanding Amount",
    "Payment Due Date",
    "Last Bill Date",
    "Last Bill Number",
    "Name",
    "Mobile",
    "Email",
    "Address",
    "Bill Number",
    "Meter Number",
    "Customer Name",
    "Address",
    "Email",
    "Mobile Number",
    "Bill Date",
    "Previous Reading",
    "Current Reading",
    "Consumption",
    "Amount",
    "Due Date",
    "Late Fee",
    "Total Amount",
    "Outstanding Amount",
    "Payment Due Date",
    "Last Bill Date",
    "Last Bill Number",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "zero",
    "double",
    "triple",
]
